worker_processes 1;
events { worker_connections 1024; }
http {
    client_body_temp_path /tmp/client_body;
    proxy_temp_path /tmp/proxy;
    fastcgi_temp_path /tmp/fastcgi;
    scgi_temp_path /tmp/scgi;
    server {
        listen 8080;
        root /workspace/source/app;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
